name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v


name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Cypress.io 
        uses: cypress-io/github-action@v2.9.7
        with: 
          start: npm start

